### ISSUE TITLE
Fax endpoint is broken

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js#13]
I followed the instructions in README.md and I tried both Browser and Node.js, neither worked.

## For browser:

```html
<!doctype>
<html>
<head>
  <title>RC JS SDK testing</title>
</head>
<body>
  <input id="myfile" type="file"/>
  <button id="test">Test</button>
  <script src="https://cdn.jsdelivr.net/jquery/2.2.0/jquery.min.js"></script>
  <script src="https://cdn.rawgit.com/ringcentral/ringcentral-js/2.0.5/build/ringcentral-bundle.js"></script>
  <script>

  function errorHandler(e) {
    console.error(e);
  }


  $(function() {
    $('#test').click(function(){

      var rcsdk = new RingCentral.SDK({ server: 'https://platform.devtest.ringcentral.com',
        appKey: 'appKey',
        appSecret: 'appSecret' });

      rcsdk.platform()
          .login({
              username: 'username', // phone number in full format
              extension: '', // leave blank if direct number is used
              password: 'password'
          })
          .then(function(response) {

            var body = {
                    to: {phoneNumber: '147258369'}, // see all available options on Developer Portal
                    faxResolution: 'High'
                },
                formData = new FormData();

            // This is the mandatory part, the name and type should always be as follows
            formData.append('json', new File([JSON.stringify(body)], 'request.json'), 'request.json', {type: 'application/json'});

            // Find the input[type=file] field on the page
            var fileField = document.getElementById('myfile');

            // Iterate through all currently selected files
            for (var i = 0, file; file = fileField.files[i]; ++i) {
                formData.append('attachment', file); // you can also use file.name instead of 'attachment'
            }

            // To send a plain text
            // formData.append('attachment', new File(['some plain text'], 'text.txt'), 'text.txt', {type: 'application/octet-stream'});

            // Send the fax
            rcsdk.platform().post('/account/~/extension/~/fax', formData).catch(errorHandler);

          }) // login then
          .catch(errorHandler);

    }); // click button
  }); // dom ready

  </script>
</body>
</html>
```

Error is:

<img width="655" alt="screen shot 2016-03-22 at 5 33 30 pm" src="https://cloud.githubusercontent.com/assets/733544/13947255/5b07b700-f054-11e5-8cbb-a73ebbf80024.png">

## For Node.js, code:

https://github.com/tylerlong/rc-commander/blob/master/rc-fax.js

In order to run, please first configure according to the readme:  https://github.com/tylerlong/rc-commander

Error is:

```
sending fax...
{ [Error: Parameter [_overheadLength] is invalid]
  apiResponse: 
   ApiResponse {
     _request: 
      Request {
        method: 'POST',
        headers: [Object],
        body: '{"_overheadLength":478,"_valueLength":72,"_lengthRetrievers":[null],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":false,"_streams":["----------------------------725655677642724183248249\\r\\nContent-Disposition: form-data; name=\\"json\\"; filename=\\"request.json\\"\\r\\nContent-Type: application/json\\r\\n\\r\\n",{"type":"Buffer","data":[123,34,116,111,34,58,123,34,112,104,111,110,101,78,117,109,98,101,114,34,58,34,49,52,55,50,53,56,51,54,57,34,125,44,34,102,97,120,82,101,115,111,108,117,116,105,111,110,34,58,34,72,105,103,104,34,125]},null,"----------------------------725655677642724183248249\\r\\nContent-Disposition: form-data; name=\\"attachment\\"; filename=\\"text.txt\\"\\r\\nContent-Type: text/plain\\r\\n\\r\\n",{"type":"Buffer","data":[115,111,109,101,32,112,108,97,105,110,32,116,101,120,116]},null,"----------------------------725655677642724183248249\\r\\nContent-Disposition: form-data; name=\\"attachment\\"; filename=\\"README.md\\"\\r\\nContent-Type: text/x-markdown\\r\\n\\r\\n",{"source":{"_readableState":{"objectMode":false,"highWaterMark":65536,"buffer":[{"type":"Buffer","data":[35,32,114,99,45,99,111,109,109,97,110,100,101,114,10,10,82,105,110,103,67,101,110,116,114,97,108,32,105,110,32,121,111,117,114,32,116,101,114,109,105,110,97,108,46,10,10,84,104,105,115,32,105,115,32,99,117,114,114,101,110,116,108,121,32,102,111,114,32,108,101,97,114,110,105,110,103,32,112,117,114,112,111,115,101,32,111,110,108,121,44,32,116,104,101,114,101,32,97,114,101,32,98,117,103,115,32,47,32,105,115,115,117,101,115,46,10,10,10,35,35,32,83,117,112,112,111,114,116,32,102,101,97,116,117,114,101,115,10,10,84,104,105,115,32,112,114,111,106,101,99,116,32,105,115,32,110,101,119,44,32,99,117,114,114,101,110,116,108,121,32,111,110,108,121,32,51,32,102,101,97,116,117,114,101,115,32,97,114,101,32,115,117,112,112,111,114,116,101,100,58,10,10,49,46,32,115,101,110,100,32,115,109,115,10,49,46,32,109,97,107,101,32,116,101,108,101,112,104,111,110,121,32,99,97,108,108,115,10,49,46,32,115,101,110,100,32,102,97,120,10,10,10,35,35,32,81,117,105,99,107,32,115,116,97,114,116,10,10,35,35,35,32,83,116,101,112,32,49,10,10,96,96,96,10,110,112,109,32,105,110,115,116,97,108,108,32,45,103,32,114,99,45,99,111,109,109,97,110,100,101,114,10,96,96,96,10,10,35,35,35,32,83,116,101,112,32,50,10,10,67,114,101,97,116,101,32,96,126,47,46,114,99,45,99,111,109,109,97,110,100,101,114,46,106,115,111,110,96,44,32,119,105,116,104,32,116,104,101,32,102,111,108,108,111,119,105,110,103,32,99,111,110,116,101,110,116,58,10,10,96,96,96,10,123,10,32,32,34,115,101,114,118,101,114,34,58,32,34,104,116,116,112,115,58,47,47,112,108,97,116,102,111,114,109,46,100,101,118,116,101,115,116,46,114,105,110,103,99,101,110,116,114,97,108,46,99,111,109,34,44,32,47,47,32,111,114,32,104,116,116,112,115,58,47,47,112,108,97,116,102,111,114,109,46,114,105,110,103,99,101,110,116,114,97,108,46,99,111,109,32,102,111,114,32,112,114,111,100,117,99,116,105,111,110,10,32,32,34,97,112,112,75,101,121,34,58,32,34,121,111,117,114,32,97,112,112,32,107,101,121,34,44,10,32,32,34,97,112,112,83,101,99,114,101,116,34,58,32,34,121,111,117,114,32,97,112,112,32,115,101,99,114,101,116,34,44,10,32,32,34,117,115,101,114,110,97,109,101,34,58,32,34,117,115,101,114,110,97,109,101,32,105,115,32,112,104,111,110,101,32,110,117,109,98,101,114,34,44,10,32,32,34,112,97,115,115,119,111,114,100,34,58,32,34,112,97,115,115,119,111,114,100,34,10,125,10,96,96,96,10,10,80,108,101,97,115,101,32,110,111,116,101,32,116,104,97,116,32,116,104,101,32,102,105,108,101,32,104,97,115,32,116,111,32,98,101,32,105,110,32,121,111,117,114,32,104,111,109,101,32,102,111,108,100,101,114,46,10,10,10,35,35,35,32,83,116,101,112,32,51,10,10,69,110,106,111,121,32,82,105,110,103,67,101,110,116,114,97,108,32,105,110,32,121,111,117,114,32,116,101,114,109,105,110,97,108,58,10,10,96,96,96,10,114,99,32,115,109,115,32,45,110,32,49,52,55,50,53,56,51,54,57,32,45,116,32,34,104,101,108,108,111,32,119,111,114,108,100,34,10,114,99,32,99,97,108,108,32,45,110,32,49,52,55,50,53,56,51,54,57,10,114,99,32,102,97,120,32,45,110,32,49,52,55,50,53,56,51,54,57,32,45,102,32,34,47,112,97,116,104,47,116,111,47,116,104,101,47,102,105,108,101,34,10,96,96,96,10,10,10,35,35,32,72,101,108,112,10,10,96,96,96,10,114,99,32,45,104,10,114,99,32,115,109,115,32,45,104,10,114,99,32,99,97,108,108,32,45,104,10,114,99,32,102,97,120,32,45,104,10,96,96,96,10]}],"length":915,"pipes":null,"pipesCount":0,"flowing":false,"ended":true,"endEmitted":false,"reading":false,"sync":false,"needReadable":false,"emittedReadable":true,"readableListening":false,"resumeScheduled":false,"defaultEncoding":"utf8","ranOut":false,"awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":null,"_events":{},"_eventsCount":3,"path":"README.md","fd":17,"flags":"r","mode":438,"autoClose":true},"dataSize":0,"maxDataSize":null,"pauseStream":true,"_maxDataSizeExceeded":false,"_released":false,"_bufferedEvents":[{"0":"pause"},{"0":"open","1":17},{"0":"readable"}],"_events":{},"_eventsCount":1},null],"_currentStream":null,"_boundary":"--------------------------725655677642724183248249"}',
        url: 'https://platform.devtest.ringcentral.com/restapi/v1.0/account/~/extension/~/fax',
        follow: 20,
        counter: 0,
        timeout: 0,
        compress: true,
        size: 0,
        agent: undefined,
        protocol: 'https:',
        hostname: 'platform.devtest.ringcentral.com',
        port: null,
        path: '/restapi/v1.0/account/~/extension/~/fax',
        auth: null,
        originalBody: '{"_overheadLength":478,"_valueLength":72,"_lengthRetrievers":[null],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":false,"_streams":["----------------------------725655677642724183248249\\r\\nContent-Disposition: form-data; name=\\"json\\"; filename=\\"request.json\\"\\r\\nContent-Type: application/json\\r\\n\\r\\n",{"type":"Buffer","data":[123,34,116,111,34,58,123,34,112,104,111,110,101,78,117,109,98,101,114,34,58,34,49,52,55,50,53,56,51,54,57,34,125,44,34,102,97,120,82,101,115,111,108,117,116,105,111,110,34,58,34,72,105,103,104,34,125]},null,"----------------------------725655677642724183248249\\r\\nContent-Disposition: form-data; name=\\"attachment\\"; filename=\\"text.txt\\"\\r\\nContent-Type: text/plain\\r\\n\\r\\n",{"type":"Buffer","data":[115,111,109,101,32,112,108,97,105,110,32,116,101,120,116]},null,"----------------------------725655677642724183248249\\r\\nContent-Disposition: form-data; name=\\"attachment\\"; filename=\\"README.md\\"\\r\\nContent-Type: text/x-markdown\\r\\n\\r\\n",{"source":{"_readableState":{"objectMode":false,"highWaterMark":65536,"buffer":[{"type":"Buffer","data":[35,32,114,99,45,99,111,109,109,97,110,100,101,114,10,10,82,105,110,103,67,101,110,116,114,97,108,32,105,110,32,121,111,117,114,32,116,101,114,109,105,110,97,108,46,10,10,84,104,105,115,32,105,115,32,99,117,114,114,101,110,116,108,121,32,102,111,114,32,108,101,97,114,110,105,110,103,32,112,117,114,112,111,115,101,32,111,110,108,121,44,32,116,104,101,114,101,32,97,114,101,32,98,117,103,115,32,47,32,105,115,115,117,101,115,46,10,10,10,35,35,32,83,117,112,112,111,114,116,32,102,101,97,116,117,114,101,115,10,10,84,104,105,115,32,112,114,111,106,101,99,116,32,105,115,32,110,101,119,44,32,99,117,114,114,101,110,116,108,121,32,111,110,108,121,32,51,32,102,101,97,116,117,114,101,115,32,97,114,101,32,115,117,112,112,111,114,116,101,100,58,10,10,49,46,32,115,101,110,100,32,115,109,115,10,49,46,32,109,97,107,101,32,116,101,108,101,112,104,111,110,121,32,99,97,108,108,115,10,49,46,32,115,101,110,100,32,102,97,120,10,10,10,35,35,32,81,117,105,99,107,32,115,116,97,114,116,10,10,35,35,35,32,83,116,101,112,32,49,10,10,96,96,96,10,110,112,109,32,105,110,115,116,97,108,108,32,45,103,32,114,99,45,99,111,109,109,97,110,100,101,114,10,96,96,96,10,10,35,35,35,32,83,116,101,112,32,50,10,10,67,114,101,97,116,101,32,96,126,47,46,114,99,45,99,111,109,109,97,110,100,101,114,46,106,115,111,110,96,44,32,119,105,116,104,32,116,104,101,32,102,111,108,108,111,119,105,110,103,32,99,111,110,116,101,110,116,58,10,10,96,96,96,10,123,10,32,32,34,115,101,114,118,101,114,34,58,32,34,104,116,116,112,115,58,47,47,112,108,97,116,102,111,114,109,46,100,101,118,116,101,115,116,46,114,105,110,103,99,101,110,116,114,97,108,46,99,111,109,34,44,32,47,47,32,111,114,32,104,116,116,112,115,58,47,47,112,108,97,116,102,111,114,109,46,114,105,110,103,99,101,110,116,114,97,108,46,99,111,109,32,102,111,114,32,112,114,111,100,117,99,116,105,111,110,10,32,32,34,97,112,112,75,101,121,34,58,32,34,121,111,117,114,32,97,112,112,32,107,101,121,34,44,10,32,32,34,97,112,112,83,101,99,114,101,116,34,58,32,34,121,111,117,114,32,97,112,112,32,115,101,99,114,101,116,34,44,10,32,32,34,117,115,101,114,110,97,109,101,34,58,32,34,117,115,101,114,110,97,109,101,32,105,115,32,112,104,111,110,101,32,110,117,109,98,101,114,34,44,10,32,32,34,112,97,115,115,119,111,114,100,34,58,32,34,112,97,115,115,119,111,114,100,34,10,125,10,96,96,96,10,10,80,108,101,97,115,101,32,110,111,116,101,32,116,104,97,116,32,116,104,101,32,102,105,108,101,32,104,97,115,32,116,111,32,98,101,32,105,110,32,121,111,117,114,32,104,111,109,101,32,102,111,108,100,101,114,46,10,10,10,35,35,35,32,83,116,101,112,32,51,10,10,69,110,106,111,121,32,82,105,110,103,67,101,110,116,114,97,108,32,105,110,32,121,111,117,114,32,116,101,114,109,105,110,97,108,58,10,10,96,96,96,10,114,99,32,115,109,115,32,45,110,32,49,52,55,50,53,56,51,54,57,32,45,116,32,34,104,101,108,108,111,32,119,111,114,108,100,34,10,114,99,32,99,97,108,108,32,45,110,32,49,52,55,50,53,56,51,54,57,10,114,99,32,102,97,120,32,45,110,32,49,52,55,50,53,56,51,54,57,32,45,102,32,34,47,112,97,116,104,47,116,111,47,116,104,101,47,102,105,108,101,34,10,96,96,96,10,10,10,35,35,32,72,101,108,112,10,10,96,96,96,10,114,99,32,45,104,10,114,99,32,115,109,115,32,45,104,10,114,99,32,99,97,108,108,32,45,104,10,114,99,32,102,97,120,32,45,104,10,96,96,96,10]}],"length":915,"pipes":null,"pipesCount":0,"flowing":false,"ended":true,"endEmitted":false,"reading":false,"sync":false,"needReadable":false,"emittedReadable":true,"readableListening":false,"resumeScheduled":false,"defaultEncoding":"utf8","ranOut":false,"awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":null,"_events":{},"_eventsCount":3,"path":"README.md","fd":17,"flags":"r","mode":438,"autoClose":true},"dataSize":0,"maxDataSize":null,"pauseStream":true,"_maxDataSizeExceeded":false,"_released":false,"_bufferedEvents":[{"0":"pause"},{"0":"open","1":17},{"0":"readable"}],"_events":{},"_eventsCount":1},null],"_currentStream":null,"_boundary":"--------------------------725655677642724183248249"}' },
     _response: 
      Response {
        url: 'https://platform.devtest.ringcentral.com/restapi/v1.0/account/~/extension/~/fax',
        status: 400,
        statusText: 'Bad Request',
        headers: [Object],
        body: [Object],
        bodyUsed: true,
        size: 0,
        ok: false,
        timeout: 0,
        _bytes: 137,
        _abort: false,
        _raw: [Object] },
     _text: '{\r\n  "message" : "Parameter [_overheadLength] is invalid",\r\n  "errorCode" : "InvalidParameter",\r\n  "parameterName" : "_overheadLength"\r\n}',
     _json: 
      { message: 'Parameter [_overheadLength] is invalid',
        errorCode: 'InvalidParameter',
        parameterName: '_overheadLength' },
     _multipart: [] },
  originalMessage: 'Response has unsuccessful status' }
```

**Comment by kirill-konshin** [comment]
I am looking into it right now.

**Comment by kirill-konshin** [comment]
Fixed in 2.0.6

**Comment by tylerlong** [comment]
Hi @kirill-konshin 

I still cannot get it working with 2.0.6

For browser, the error is:

<img width="715" alt="screen shot 2016-03-25 at 2 43 39 pm" src="https://cloud.githubusercontent.com/assets/733544/14039497/07909fb0-f298-11e5-9267-8bf8d615cf49.png">


For node.js, the error is:

```
{ [Error: Cannot calculate proper length in synchronous way.]
  apiResponse: 
   ApiResponse {
     _request: 
      Body {
        method: 'POST',
        headers: [Object],
        url: 'https://platform.ringcentral.com/restapi/v1.0/account/~/extension/~/fax',
        follow: 20,
        compress: true,
        counter: 0,
        agent: undefined,
        body: [Object],
        bodyUsed: false,
        size: 0,
        timeout: 0,
        _raw: [],
        _abort: false,
        protocol: 'https:',
        hostname: 'platform.ringcentral.com',
        port: null,
        path: '/restapi/v1.0/account/~/extension/~/fax',
        auth: null,
        originalBody: [Object] },
     _response: undefined,
     _text: undefined,
     _json: null,
     _multipart: [] },
  originalMessage: 'Cannot calculate proper length in synchronous way.' }
```

Could you please advise?

**Comment by kirill-konshin** [comment]
Instead of 

```js
to: {phoneNumber: '147258369'}
```

you should use

```js
to: [{phoneNumber: '147258369'}] // note the array
```

**Comment by tylerlong** [comment]
I haven't tested the browser yet. But I still cannot get the node.js code working.

Here is the code:  https://github.com/tylerlong/rc-commander/blob/master/rc-fax.js

Here is the error message:

```
➜  rc-commander git:(master) ✗ node rc.js fax -n 16508370092 -f README.pdf
sending fax...
{ [Error: Cannot calculate proper length in synchronous way.]
  apiResponse: 
   ApiResponse {
     _request: 
      Body {
        method: 'POST',
        headers: [Object],
        url: 'https://platform.ringcentral.com/restapi/v1.0/account/~/extension/~/fax',
        follow: 20,
        compress: true,
        counter: 0,
        agent: undefined,
        body: [Object],
        bodyUsed: false,
        size: 0,
        timeout: 0,
        _raw: [],
        _abort: false,
        protocol: 'https:',
        hostname: 'platform.ringcentral.com',
        port: null,
        path: '/restapi/v1.0/account/~/extension/~/fax',
        auth: null,
        originalBody: [Object] },
     _response: undefined,
     _text: undefined,
     _json: null,
     _multipart: [] },
  originalMessage: 'Cannot calculate proper length in synchronous way.' }
```

**Comment by tylerlong** [comment]
The browser code doesn't work either:

```html
<!doctype>
<html>
<head>
  <title>RC JS SDK testing</title>
</head>
<body>
  <input id="myfile" type="file"/>
  <button id="test">Test</button>
  <script src="https://cdn.jsdelivr.net/jquery/2.2.0/jquery.min.js"></script>
  <script src="https://cdn.rawgit.com/ringcentral/ringcentral-js/2.0.6/build/ringcentral-bundle.js"></script>
  <script>

  function errorHandler(e) {
    console.error(e);
  }


  $(function() {
    $('#test').click(function(){

      var rcsdk = new RingCentral.SDK({ server: 'https://platform.ringcentral.com',
        appKey: 'appKey',
        appSecret: 'appSecret' });

      rcsdk.platform()
          .login({
              username: 'username', // phone number in full format
              extension: '', // leave blank if direct number is used
              password: 'password'
          })
          .then(function(response) {

            var body = {
                    to: [{phoneNumber: '147258369'}], // see all available options on Developer Portal
                    faxResolution: 'High'
                },
                formData = new FormData();

            // This is the mandatory part, the name and type should always be as follows
            formData.append('json', new File([JSON.stringify(body)], 'request.json'), 'request.json', {type: 'application/json'});

            // Find the input[type=file] field on the page
            var fileField = document.getElementById('myfile');

            // Iterate through all currently selected files
            for (var i = 0, file; file = fileField.files[i]; ++i) {
                formData.append('attachment', file); // you can also use file.name instead of 'attachment'
            }

            // To send a plain text
            // formData.append('attachment', new File(['some plain text'], 'text.txt'), 'text.txt', {type: 'application/octet-stream'});

            // Send the fax
            rcsdk.platform().post('/account/~/extension/~/fax', formData).catch(errorHandler);

          }) // login then
          .catch(errorHandler);

    }); // click button
  }); // dom ready

  </script>
</body>
</html>
```

Error message is:

![screen shot 2016-03-25 at 9 19 41 pm](https://cloud.githubusercontent.com/assets/733544/14044808/5c7cdc64-f2cf-11e5-803c-f94ad0ffd430.png)


Maybe there are some typos in my code. Do let me know, currently I have no idea why it doesn't work.

**Comment by kirill-konshin** [comment]
I was able to send with latest SDK:

```js
var sdk = new SDK({
    appKey: 'xxx',
    appSecret: 'xxx',
    server: SDK.server.sandbox
});

var formData = new FormData();

var body = {
    to: [{phoneNumber: 'xxx'}],
    faxResolution: 'High'
};

formData.append('json', new Buffer(JSON.stringify(body)), {filename: 'request.json', contentType: 'application/json'});

formData.append('attachment', new Buffer('some plain text'), {filename: 'text.txt', contentType: 'text/plain'});

console.log('sending fax...');

sdk.platform()
    .login({
        username: 'xxx',
        extension: null,
        password: 'xxx',
    })
    .then(function(response) {

        console.log('Login successful');

        return sdk.platform()
            .post('/account/~/extension/~/fax', formData)
            .then(function() {
                console.log('fax sent');
            });

    })
    .catch(function(e) {
        console.error(e.apiResponse.request());
        console.error(e.stack);
    });
```

**Comment by tylerlong** [comment]
@kirill-konshin  I tried your code and it did work!  Thank you very much!

But I am not able to send a a file from file system. I am going to create a new issue to track it instead.
